

> MATRICES BASICS



In [ ]:
# MATRICS ARE NUMBERS OR EQUATIONS ARRANGED INTO ROWS AND/OR COLUMNS

In [ ]:
import numpy as np

In [ ]:
# NUMPY ARRAYS ARE NOTHING BUT MATRICES
matrix1=np.array([[180,200,220],[24,36,40],[12,18,20]])
matrix2=np.array([[80,90,100],[10,16,20],[8,10,10]])

In [ ]:
# TO SUBTRACT TO MATRICES USE
matrix1-matrix2

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [ ]:
# BROADCASTING IN NUMPY
# CAUTION DO NOT USE
# HERE WE CAN SEE THAT MATRICES HAVE NOT MULTIPLIED BY DOT PRODUCT THIS IS CALLED BROADCASTING WHICH IS NUMPY TECHNIQUE
# SO HERE IT ASSUMES SINCE IN MATRIX 1 IT IS ONLY ONE ARRAY AND IN MATRIX 2 IT IS 3 ARRAYS, IT WILL CONVERT MATRIX 1 TO  3 ARRAYS WHERE IT WILL REPEAT THE 1 SAME ARRAY 3 TIMES
matrix1=np.array([100,200,300])
matrix2=np.array([[30,40,50],[10,15,20],[5,10,25]])
matrix1*matrix2

array([[ 3000,  8000, 15000],
       [ 1000,  3000,  6000],
       [  500,  2000,  7500]])

In [ ]:
# DOT PRODUCT
# SO WE USE DOT FUNCTION TO PERFORM DOT PRODUCT MULTIPLICATION USING DOT FUNCTION
matrix1=np.array([100,200,300])
matrix2=np.array([[30,40,50],[10,15,20],[5,10,25]])
np.dot(matrix1,matrix2)

array([ 6500, 10000, 16500])

In [ ]:
# EXERCISE
revenue=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
currency=np.array(75)
np.dot(revenue,currency)

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [ ]:
units_sold=np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit=np.array([20,30,15])
np.dot(price_per_unit,units_sold)

array([1900, 2640, 1430])